# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\DBMS\ui\other.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # 設置主視窗的基本屬性
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        # 創建中央小部件
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 創建標籤顯示標題
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 50, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        # 創建表格小部件
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(120, 130, 591, 361))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)  # 設置列數
        self.tableWidget.setRowCount(11)    # 設置行數
        
        # 設置表格內容唯讀
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        
        # 固定表格大小
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        self.tableWidget.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)

        # 設置表格的行標題
        for i in range(11):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
        
        # 設置表格的列標題
        for i in range(3):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(i, item)
        
        # 填充表格內容
        for row in range(11):
            for col in range(3):
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(row, col, item)
        
        # 設置表格的默認列寬和行高
        self.tableWidget.horizontalHeader().setDefaultSectionSize(191)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        
        # 創建返回主畫面的按鈕
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 520, 102, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        
        # 設置主視窗的中央小部件
        MainWindow.setCentralWidget(self.centralwidget)
        
        # 創建菜單欄和狀態欄
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # 設置界面文本
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "其他監理站"))
        self.tableWidget.setSortingEnabled(False)
        
        # 設置表格的列標題
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "所站名稱"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "地址"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "電話"))
        
        # 填充表格的內容
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        data = [
            ("臺北市區監理所", "臺北市松山區八德路四段21號", "02-27630155"),
            ("士林監理站", "臺北市士林區承德路五段80號", "02-28314155"),
            ("基隆監理站", "基隆市七堵區實踐路296號", "02-24515311"),
            ("連江監理站", "連江縣南竿鄉津沙村155號", "0836-22694"),
            ("金門監理站", "金門縣金湖鎮黃海路六之一號", "082-332407"),
            ("臺北區監理所", "新北市樹林區中正路248巷7號", "02-26884366"),
            ("蘆洲監理站", "新北市蘆洲區中山二路163號", "02-22886883"),
            ("板橋監理站", "新北市中和區中山路三段116號", "02-22227835"),
            ("宜蘭監理站", "宜蘭縣五結鄉中正路二段9號", "03-9658461"),
            ("花蓮監理站", "花蓮縣吉安鄉中正路二段152號", "03-8523166"),
            ("玉里監理分站", "花蓮縣玉里鎮中華路427號", "03-8883161")
        ]
        for row, (name, address, phone) in enumerate(data):
            self.tableWidget.item(row, 0).setText(_translate("MainWindow", name))
            self.tableWidget.item(row, 1).setText(_translate("MainWindow", address))
            self.tableWidget.item(row, 2).setText(_translate("MainWindow", phone))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        
        # 設置返回按鈕的文本
        self.pushButton_6.setText(_translate("MainWindow", "返回主畫面"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
